export const PROMPT_TEMPLATE_GENERAL_MODULE = '通用';
export const PROMPT_TEMPLATE_MODULE_CASE_GENERATION = '案例生成';
export const PROMPT_TEMPLATE_MODULE_REQUIREMENT_ANALYSIS = '需求分析';
export const PROMPT_TEMPLATE_MODULE_CASE_ANALYSIS = '案例分析';
export const PROMPT_TEMPLATE_MODULE_API_AUTOMATION = '接口自动化';
export const PROMPT_TEMPLATE_MODULE_AI_AGENT = 'AI助手';
export const PROMPT_TEMPLATE_MODULE_POLICY_CHECK = 'AI保单核对';

export const PROMPT_TEMPLATE_MODULES = [
  PROMPT_TEMPLATE_GENERAL_MODULE,
  PROMPT_TEMPLATE_MODULE_CASE_GENERATION,
  PROMPT_TEMPLATE_MODULE_REQUIREMENT_ANALYSIS,
  PROMPT_TEMPLATE_MODULE_CASE_ANALYSIS,
  PROMPT_TEMPLATE_MODULE_API_AUTOMATION,
  PROMPT_TEMPLATE_MODULE_AI_AGENT,
  PROMPT_TEMPLATE_MODULE_POLICY_CHECK,
] as const;

export type PromptTemplateModule = (typeof PROMPT_TEMPLATE_MODULES)[number];

export function getPromptTemplateModuleLabel(module?: string | null): string {
  return module?.trim() || PROMPT_TEMPLATE_GENERAL_MODULE;
}
